server:
  tomcat:
    max-connections: 20000
    max-threads: 1000
  #port: 8000
  port: 8088

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: local
    #active: prod





